import * as Types from '../../__generated__/globalTypes';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
import { UserLayout_CurrentUserFragmentDoc, UserLayout_UserFragmentDoc } from '../../ui/__generated__/UserLayout.graphql';
import { PostComposer_RecordFragmentDoc } from '../../ui/__generated__/PostComposer.graphql';
import { PostComment_PostFragmentDoc } from '../../ui/__generated__/GqlPostComment.graphql';
export type RecordRouteQueryVariables = Types.Exact<{
  recordId: Types.Scalars['ID'];
}>;


export type RecordRouteQuery = { __typename?: 'Query', layoutCurrentUser: { __typename?: 'User', name: string | null } | null, currentUser: { __typename?: 'User', databaseId: string, isTwitterConnected: boolean | null } | null, record: { __typename?: 'Record', databaseId: string, title: string | null, updatedAt: any | null, rating: number | null, statusType: Types.StatusType | null, status: string | null, user: { __typename?: 'User', isCurrentUser: boolean, name: string | null, categories: Array<{ __typename?: 'Category', databaseId: string, name: string }> } | null, layoutUser: { __typename?: 'User', name: string | null, joinedAt: any | null, isCurrentUser: boolean, recordCount: number | null, postCount: number | null } | null, category: { __typename?: 'Category', databaseId: string } | null } | null };

export type RecordRoute_RecordFragment = { __typename?: 'Record', databaseId: string, title: string | null, updatedAt: any | null, rating: number | null, statusType: Types.StatusType | null, status: string | null, user: { __typename?: 'User', isCurrentUser: boolean, name: string | null, categories: Array<{ __typename?: 'Category', databaseId: string, name: string }> } | null, layoutUser: { __typename?: 'User', name: string | null, joinedAt: any | null, isCurrentUser: boolean, recordCount: number | null, postCount: number | null } | null, category: { __typename?: 'Category', databaseId: string } | null };

export type RecordRoute_HeaderFragment = { __typename?: 'Record', title: string | null, rating: number | null, user: { __typename?: 'User', isCurrentUser: boolean, categories: Array<{ __typename?: 'Category', databaseId: string, name: string }> } | null, category: { __typename?: 'Category', databaseId: string } | null };

export type RecordRoute_Header_CategoryFragment = { __typename?: 'Category', databaseId: string, name: string };

export type RecordRoute_PostsQueryVariables = Types.Exact<{
  recordId: Types.Scalars['ID'];
}>;


export type RecordRoute_PostsQuery = { __typename?: 'Query', record: { __typename?: 'Record', posts: { __typename?: 'PostConnection', nodes: Array<{ __typename?: 'Post', databaseId: string, statusType: Types.StatusType | null, status: string | null, comment: string | null, containsSpoiler: boolean | null, updatedAt: any | null }> } } | null };

export type RecordRoute_PostFragment = { __typename?: 'Post', databaseId: string, statusType: Types.StatusType | null, status: string | null, comment: string | null, containsSpoiler: boolean | null, updatedAt: any | null };

export type RecordRoute_UpdateTitleMutationVariables = Types.Exact<{
  input: Types.UpdateRecordTitleInput;
}>;


export type RecordRoute_UpdateTitleMutation = { __typename?: 'Mutation', updateRecordTitle: { __typename?: 'UpdateRecordTitleResult', record: { __typename?: 'Record', databaseId: string, title: string | null, updatedAt: any | null, rating: number | null, statusType: Types.StatusType | null, status: string | null, user: { __typename?: 'User', isCurrentUser: boolean, name: string | null, categories: Array<{ __typename?: 'Category', databaseId: string, name: string }> } | null, layoutUser: { __typename?: 'User', name: string | null, joinedAt: any | null, isCurrentUser: boolean, recordCount: number | null, postCount: number | null } | null, category: { __typename?: 'Category', databaseId: string } | null } } };

export type RecordRoute_UpdateCategoryMutationVariables = Types.Exact<{
  input: Types.UpdateRecordCategoryIdInput;
}>;


export type RecordRoute_UpdateCategoryMutation = { __typename?: 'Mutation', updateRecordCategoryId: { __typename?: 'UpdateRecordCategoryIdResult', record: { __typename?: 'Record', databaseId: string, title: string | null, updatedAt: any | null, rating: number | null, statusType: Types.StatusType | null, status: string | null, user: { __typename?: 'User', isCurrentUser: boolean, name: string | null, categories: Array<{ __typename?: 'Category', databaseId: string, name: string }> } | null, layoutUser: { __typename?: 'User', name: string | null, joinedAt: any | null, isCurrentUser: boolean, recordCount: number | null, postCount: number | null } | null, category: { __typename?: 'Category', databaseId: string } | null } } };

export type RecordRoute_UpdateRatingMutationVariables = Types.Exact<{
  input: Types.UpdateRecordRatingInput;
}>;


export type RecordRoute_UpdateRatingMutation = { __typename?: 'Mutation', updateRecordRating: { __typename?: 'UpdateRecordRatingResult', record: { __typename?: 'Record', databaseId: string, title: string | null, updatedAt: any | null, rating: number | null, statusType: Types.StatusType | null, status: string | null, user: { __typename?: 'User', isCurrentUser: boolean, name: string | null, categories: Array<{ __typename?: 'Category', databaseId: string, name: string }> } | null, layoutUser: { __typename?: 'User', name: string | null, joinedAt: any | null, isCurrentUser: boolean, recordCount: number | null, postCount: number | null } | null, category: { __typename?: 'Category', databaseId: string } | null } } };

export type RecordRoute_CreatePostMutationVariables = Types.Exact<{
  input: Types.CreatePostInput;
}>;


export type RecordRoute_CreatePostMutation = { __typename?: 'Mutation', createPost: { __typename?: 'CreatePostResult', post: { __typename?: 'Post', databaseId: string } } };

export type RecordRoute_DeletePostMutationVariables = Types.Exact<{
  input: Types.DeletePostInput;
}>;


export type RecordRoute_DeletePostMutation = { __typename?: 'Mutation', deletePost: { __typename?: 'DeletePostResult', record: { __typename?: 'Record', databaseId: string, title: string | null, updatedAt: any | null, rating: number | null, statusType: Types.StatusType | null, status: string | null, user: { __typename?: 'User', isCurrentUser: boolean, name: string | null, categories: Array<{ __typename?: 'Category', databaseId: string, name: string }> } | null, layoutUser: { __typename?: 'User', name: string | null, joinedAt: any | null, isCurrentUser: boolean, recordCount: number | null, postCount: number | null } | null, category: { __typename?: 'Category', databaseId: string } | null } | null } };

export type RecordRoute_DeleteRecordMutationVariables = Types.Exact<{
  input: Types.DeleteRecordInput;
}>;


export type RecordRoute_DeleteRecordMutation = { __typename?: 'Mutation', deleteRecord: { __typename?: 'DeleteRecordResult', deleted: boolean } };

export const RecordRoute_Header_CategoryFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"RecordRoute_header_category"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Category"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"databaseId"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]} as unknown as DocumentNode<RecordRoute_Header_CategoryFragment, unknown>;
export const RecordRoute_HeaderFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"RecordRoute_header"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Record"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"rating"}},{"kind":"Field","name":{"kind":"Name","value":"user"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"isCurrentUser"}},{"kind":"Field","name":{"kind":"Name","value":"categories"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"RecordRoute_header_category"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"category"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"databaseId"}}]}}]}}]} as unknown as DocumentNode<RecordRoute_HeaderFragment, unknown>;
export const RecordRoute_RecordFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"RecordRoute_record"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Record"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"databaseId"}},{"kind":"Field","name":{"kind":"Name","value":"user"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"isCurrentUser"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","alias":{"kind":"Name","value":"layoutUser"},"name":{"kind":"Name","value":"user"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"UserLayout_user"}}]}},{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"RecordRoute_header"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"PostComposer_record"}}]}}]} as unknown as DocumentNode<RecordRoute_RecordFragment, unknown>;
export const RecordRoute_PostFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"RecordRoute_post"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Post"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"databaseId"}},{"kind":"Field","name":{"kind":"Name","value":"statusType"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"comment"}},{"kind":"Field","name":{"kind":"Name","value":"containsSpoiler"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"PostComment_post"}}]}}]} as unknown as DocumentNode<RecordRoute_PostFragment, unknown>;
export const RecordRouteDocument = {"kind":"Document", "definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"RecordRoute"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"recordId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"layoutCurrentUser"},"name":{"kind":"Name","value":"currentUser"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"UserLayout_currentUser"}}]}},{"kind":"Field","name":{"kind":"Name","value":"currentUser"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"databaseId"}},{"kind":"Field","name":{"kind":"Name","value":"isTwitterConnected"}}]}},{"kind":"Field","name":{"kind":"Name","value":"record"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"recordId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"RecordRoute_record"}}]}}]}},...UserLayout_CurrentUserFragmentDoc.definitions,...RecordRoute_RecordFragmentDoc.definitions,...UserLayout_UserFragmentDoc.definitions,...RecordRoute_HeaderFragmentDoc.definitions,...RecordRoute_Header_CategoryFragmentDoc.definitions,...PostComposer_RecordFragmentDoc.definitions]} as unknown as DocumentNode<RecordRouteQuery, RecordRouteQueryVariables>;
export const RecordRoute_PostsDocument = {"kind":"Document", "definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"RecordRoute_posts"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"recordId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"record"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"recordId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"posts"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"beforeId"},"value":{"kind":"NullValue"}},{"kind":"Argument","name":{"kind":"Name","value":"count"},"value":{"kind":"NullValue"}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodes"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"RecordRoute_post"}}]}}]}}]}}]}},...RecordRoute_PostFragmentDoc.definitions,...PostComment_PostFragmentDoc.definitions]} as unknown as DocumentNode<RecordRoute_PostsQuery, RecordRoute_PostsQueryVariables>;
export const RecordRoute_UpdateTitleDocument = {"kind":"Document", "definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"RecordRoute_updateTitle"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"UpdateRecordTitleInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateRecordTitle"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"record"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"RecordRoute_record"}}]}}]}}]}},...RecordRoute_RecordFragmentDoc.definitions,...UserLayout_UserFragmentDoc.definitions,...RecordRoute_HeaderFragmentDoc.definitions,...RecordRoute_Header_CategoryFragmentDoc.definitions,...PostComposer_RecordFragmentDoc.definitions]} as unknown as DocumentNode<RecordRoute_UpdateTitleMutation, RecordRoute_UpdateTitleMutationVariables>;
export const RecordRoute_UpdateCategoryDocument = {"kind":"Document", "definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"RecordRoute_updateCategory"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"UpdateRecordCategoryIdInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateRecordCategoryId"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"record"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"RecordRoute_record"}}]}}]}}]}},...RecordRoute_RecordFragmentDoc.definitions,...UserLayout_UserFragmentDoc.definitions,...RecordRoute_HeaderFragmentDoc.definitions,...RecordRoute_Header_CategoryFragmentDoc.definitions,...PostComposer_RecordFragmentDoc.definitions]} as unknown as DocumentNode<RecordRoute_UpdateCategoryMutation, RecordRoute_UpdateCategoryMutationVariables>;
export const RecordRoute_UpdateRatingDocument = {"kind":"Document", "definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"RecordRoute_updateRating"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"UpdateRecordRatingInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateRecordRating"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"record"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"RecordRoute_record"}}]}}]}}]}},...RecordRoute_RecordFragmentDoc.definitions,...UserLayout_UserFragmentDoc.definitions,...RecordRoute_HeaderFragmentDoc.definitions,...RecordRoute_Header_CategoryFragmentDoc.definitions,...PostComposer_RecordFragmentDoc.definitions]} as unknown as DocumentNode<RecordRoute_UpdateRatingMutation, RecordRoute_UpdateRatingMutationVariables>;
export const RecordRoute_CreatePostDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"RecordRoute_createPost"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"CreatePostInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createPost"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"post"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"databaseId"}}]}}]}}]}}]} as unknown as DocumentNode<RecordRoute_CreatePostMutation, RecordRoute_CreatePostMutationVariables>;
export const RecordRoute_DeletePostDocument = {"kind":"Document", "definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"RecordRoute_deletePost"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"DeletePostInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"deletePost"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"record"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"RecordRoute_record"}}]}}]}}]}},...RecordRoute_RecordFragmentDoc.definitions,...UserLayout_UserFragmentDoc.definitions,...RecordRoute_HeaderFragmentDoc.definitions,...RecordRoute_Header_CategoryFragmentDoc.definitions,...PostComposer_RecordFragmentDoc.definitions]} as unknown as DocumentNode<RecordRoute_DeletePostMutation, RecordRoute_DeletePostMutationVariables>;
export const RecordRoute_DeleteRecordDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"RecordRoute_deleteRecord"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"DeleteRecordInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"deleteRecord"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"deleted"}}]}}]}}]} as unknown as DocumentNode<RecordRoute_DeleteRecordMutation, RecordRoute_DeleteRecordMutationVariables>;