import * as Types from '../../__generated__/globalTypes';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
import { UserLayout_CurrentUserFragmentDoc, UserLayout_UserFragmentDoc } from '../../ui/__generated__/UserLayout.graphql';
import { Library_UserFragmentDoc, Library_RecordFragmentDoc } from '../../ui/__generated__/Library.graphql';
import { LibraryFilter_CategoryFragmentDoc, LibraryFilter_RecordFiltersFragmentDoc, LibraryFilter_RecordFilterFragmentDoc } from '../../ui/__generated__/LibraryFilter.graphql';
export type UserRouteQueryVariables = Types.Exact<{
  username: Types.Scalars['String'];
  statusTypeFilter: Types.InputMaybe<Types.StatusType>;
  categoryIdFilter: Types.InputMaybe<Types.Scalars['ID']>;
  recordOrder: Types.RecordOrder;
}>;


export type UserRouteQuery = { __typename?: 'Query', currentUser: { __typename?: 'User', name: string | null } | null, user: { __typename?: 'User', name: string | null, joinedAt: any | null, isCurrentUser: boolean, recordCount: number | null, postCount: number | null, categories: Array<{ __typename?: 'Category', databaseId: string, name: string }>, recordFilters: { __typename?: 'RecordFilters', totalCount: number, filteredCount: number, statusType: { __typename?: 'RecordFilter', allCount: number, items: Array<{ __typename?: 'RecordFilterItem', key: string, count: number }> }, categoryId: { __typename?: 'RecordFilter', allCount: number, items: Array<{ __typename?: 'RecordFilterItem', key: string, count: number }> } }, records: { __typename?: 'RecordConnection', nodes: Array<{ __typename?: 'Record', databaseId: string, title: string | null, statusType: Types.StatusType | null, status: string | null, rating: number | null, updatedAt: any | null, hasNewerEpisode: boolean | null }> } } | null };


export const UserRouteDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"UserRoute"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"username"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"statusTypeFilter"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"StatusType"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"categoryIdFilter"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"recordOrder"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"RecordOrder"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"currentUser"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"UserLayout_currentUser"}}]}},{"kind":"Field","alias":{"kind":"Name","value":"user"},"name":{"kind":"Name","value":"userByName"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"name"},"value":{"kind":"Variable","name":{"kind":"Name","value":"username"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"UserLayout_user"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"Library_user"}}]}}]}},...UserLayout_CurrentUserFragmentDoc.definitions,...UserLayout_UserFragmentDoc.definitions,...Library_UserFragmentDoc.definitions,...LibraryFilter_CategoryFragmentDoc.definitions,...LibraryFilter_RecordFiltersFragmentDoc.definitions,...LibraryFilter_RecordFilterFragmentDoc.definitions,...Library_RecordFragmentDoc.definitions]} as unknown as DocumentNode<UserRouteQuery, UserRouteQueryVariables>;