import * as Types from '../../__generated__/globalTypes';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
import { GqlWorkViewsFragmentDoc, GqlWorkViews_PostConnectionFragmentDoc, GqlWorkViews_EpisodeFragmentDoc } from '../../ui/__generated__/GqlWorkViews.graphql';
import { WeeklyChartFragmentDoc } from '../../ui/__generated__/GqlWeeklyChart.graphql';
export type WorkRouteQueryVariables = Types.Exact<{
  title: Types.Scalars['String'];
}>;


export type WorkRouteQuery = { __typename?: 'Query', work?: { __typename?: 'Work', id: string, title?: string | null, imageUrl?: string | null, recordCount?: number | null, posts: { __typename?: 'PostConnection', hasMore: boolean, nodes: Array<{ __typename?: 'Post', id: string, statusType?: Types.StatusType | null, status?: string | null, comment?: string | null, updatedAt?: any | null, containsSpoiler?: boolean | null, user?: { __typename?: 'User', name?: string | null } | null, record?: { __typename?: 'Record', title?: string | null } | null }> }, record?: { __typename?: 'Record', id: string, statusType?: Types.StatusType | null, status?: string | null } | null, episodes?: Array<{ __typename?: 'Episode', number: number, postCount?: number | null }> | null, metadata?: { __typename?: 'WorkMetadata', studioNames?: Array<string> | null, source?: Types.SourceType | null, websiteUrl?: string | null, namuwikiUrl?: string | null, annUrl?: string | null, schedules?: Array<{ __typename?: 'WorkSchedule', country: string, date?: any | null, datePrecision?: Types.DatePrecision | null }> | null } | null } | null, weeklyWorksChart: Array<{ __typename?: 'WorksChartItem', rank: number, diff?: number | null, sign?: number | null, work: { __typename?: 'Work', id: string, title?: string | null, imageUrl?: string | null } }> };

export type WorkRoute_MorePostsQueryVariables = Types.Exact<{
  workId: Types.Scalars['ID'];
  beforeId?: Types.InputMaybe<Types.Scalars['ID']>;
}>;


export type WorkRoute_MorePostsQuery = { __typename?: 'Query', work?: { __typename?: 'Work', posts: { __typename?: 'PostConnection', hasMore: boolean, nodes: Array<{ __typename?: 'Post', id: string, statusType?: Types.StatusType | null, status?: string | null, comment?: string | null, updatedAt?: any | null, containsSpoiler?: boolean | null, user?: { __typename?: 'User', name?: string | null } | null, record?: { __typename?: 'Record', title?: string | null } | null }> } } | null };

export type WorkRoute_RefetchQueryVariables = Types.Exact<{
  id: Types.Scalars['ID'];
}>;


export type WorkRoute_RefetchQuery = { __typename?: 'Query', work?: { __typename?: 'Work', id: string, title?: string | null, imageUrl?: string | null, recordCount?: number | null, posts: { __typename?: 'PostConnection', hasMore: boolean, nodes: Array<{ __typename?: 'Post', id: string, statusType?: Types.StatusType | null, status?: string | null, comment?: string | null, updatedAt?: any | null, containsSpoiler?: boolean | null, user?: { __typename?: 'User', name?: string | null } | null, record?: { __typename?: 'Record', title?: string | null } | null }> }, record?: { __typename?: 'Record', id: string, statusType?: Types.StatusType | null, status?: string | null } | null, episodes?: Array<{ __typename?: 'Episode', number: number, postCount?: number | null }> | null, metadata?: { __typename?: 'WorkMetadata', studioNames?: Array<string> | null, source?: Types.SourceType | null, websiteUrl?: string | null, namuwikiUrl?: string | null, annUrl?: string | null, schedules?: Array<{ __typename?: 'WorkSchedule', country: string, date?: any | null, datePrecision?: Types.DatePrecision | null }> | null } | null } | null };


export const WorkRouteDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"WorkRoute"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"title"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"work"},"name":{"kind":"Name","value":"workByTitle"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"title"},"value":{"kind":"Variable","name":{"kind":"Name","value":"title"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"GqlWorkViews"}},{"kind":"Field","name":{"kind":"Name","value":"posts"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"count"},"value":{"kind":"IntValue","value":"10"}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"GqlWorkViews_postConnection"}}]}}]}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"WeeklyChart"}}]}},...GqlWorkViewsFragmentDoc.definitions,...GqlWorkViews_PostConnectionFragmentDoc.definitions,...WeeklyChartFragmentDoc.definitions]} as unknown as DocumentNode<WorkRouteQuery, WorkRouteQueryVariables>;
export const WorkRoute_MorePostsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"WorkRoute_morePosts"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"workId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"beforeId"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"work"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"workId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"posts"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"beforeId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"beforeId"}}},{"kind":"Argument","name":{"kind":"Name","value":"count"},"value":{"kind":"IntValue","value":"10"}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"GqlWorkViews_postConnection"}}]}}]}}]}},...GqlWorkViews_PostConnectionFragmentDoc.definitions]} as unknown as DocumentNode<WorkRoute_MorePostsQuery, WorkRoute_MorePostsQueryVariables>;
export const WorkRoute_RefetchDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"WorkRoute_refetch"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"work"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"GqlWorkViews"}},{"kind":"Field","name":{"kind":"Name","value":"posts"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"count"},"value":{"kind":"IntValue","value":"10"}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"GqlWorkViews_postConnection"}}]}}]}}]}},...GqlWorkViewsFragmentDoc.definitions,...GqlWorkViews_PostConnectionFragmentDoc.definitions]} as unknown as DocumentNode<WorkRoute_RefetchQuery, WorkRoute_RefetchQueryVariables>;