FROM node:22

RUN apt-get update && apt-get install -y --no-install-recommends \
		imagemagick \
		jpegoptim \
	&& rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm@^7

WORKDIR /app/backend-ts

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ../
COPY patches ../patches
COPY backend-ts/package.json ./
RUN pnpm install --prod --frozen-lockfile

COPY backend-ts .

ENTRYPOINT ["node", "dist/main.js"]
