# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-12 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_workindex_blacklisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAttributeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=20)),
                ('value', models.TextField()),
            ],
        ),
    ]
