# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-04 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_work_original_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
