# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 20:20
from __future__ import unicode_literals

from django.db import migrations, models


def fill_original_image_filename(apps, schema_editor):
    Work = apps.get_model('work', 'Work')
    for work in Work.objects.exclude(image_filename=None):
        work.original_image_filename = work.image_filename.replace('/thumb/', '/')
        work.save()


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20160618_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='original_image_filename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(fill_original_image_filename),
    ]
