# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-10 22:30
from __future__ import unicode_literals

import yaml
import django.contrib.postgres.fields.jsonb
from django.db import migrations


def fill_metadata(apps, schema_editor):
    Work = apps.get_model('work', 'Work')
    for work in Work.objects.exclude(raw_metadata=None):
        work.metadata = yaml.load(work.raw_metadata)
        work.save()


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_work_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.RunPython(fill_metadata),
    ]
