# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-24 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_work_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image_center_y',
            field=models.FloatField(default=0.0),
        ),
    ]
