FROM node:22-slim

RUN mkdir /app
WORKDIR /app

COPY ./frontend-server/dist /app/frontend-server/dist
COPY ./frontend/dist /app/frontend/dist

ENV NODE_ENV production
ENV ANIMETA_FRONTEND_DIST_PATH /app/frontend/dist
ENV ANIMETA_FRONTEND_APP_PROVIDER vite

CMD ["node", "frontend-server/dist/bundle.js"]
